### ISSUE TITLE
bug: tasks.json multi-line pattern `message` does not apply to all problems

### ISSUE THREAD

**Issue by portus-zephyr** [stevearc/overseer.nvim#247]
### Neovim version (nvim -v)

0.9.4

### Operating system/version

EndeavourOS

### Describe the bug

```json
"pattern": [
          {
            "regexp": "^(\\w+\\sleak)\\sof.*from:",
            "message": 1
          },
          {
            "regexp": "^\\s+#\\d\\s\\w+\\sin\\s\\w+\\s(.+):(\\d+)$",
            "file": 1,
            "line": 2,
            "loop": true
          }
]
```
If `message` is defined in the first pattern group, then all found problems will use default `message` (the content of all lines matched by the second group) and not the `message` set by the first group.

![image](https://github.com/stevearc/overseer.nvim/assets/66728045/8d769487-8302-4c9a-b9b2-d8dd3f5babce)

In VSCode, the default behavior is for the `message` in the first group to apply to all problems matched in the second group.

![image](https://github.com/stevearc/overseer.nvim/assets/66728045/0fc30ceb-9d52-44ad-bd8e-c4015e1d6493)

The above problems should all have "direct leak" as message.

### What is the severity of this bug?

tolerable (can work around it)

### Steps To Reproduce

1. set tasks.json to above
2. run overseer vscode task

### Expected Behavior

The above problems should all have "direct leak" as message.

### Minimal example file

tasks.json
```json
{
  "version": "2.0.0",
  "tasks": [
    {
      "label": "(vscode) make run current file",
      "type": "shell",
      "command": "make",
      "args": [
        "run",
        "filename=${fileBasenameNoExtension}"
      ],
      "group": "test",
      "problemMatcher": {
        "fileLocation": [
          "relative",
          "${cwd}"
        ],
        "owner": "cpp",
        "pattern": [
          {
            "regexp": "^(\\w+\\sleak)\\sof.*from:",
            "message": 1
          },
          {
            "regexp": "^\\s+#\\d\\s\\w+\\sin\\s\\w+\\s(.+):(\\d+)$",
            "file": 1,
            "line": 2,
            "loop": true
          }
        ]
      }
    },
  ]
}

```

sample cmd output to match

```txt

=================================================================
==18072==ERROR: LeakSanitizer: detected memory leaks

Direct leak of 40 byte(s) in 1 object(s) allocated from:
    #0 0x7fc53d6e0cc1 in __interceptor_calloc /usr/src/debug/gcc/gcc/libsanitizer/asan/asan_malloc_linux.cpp:77
    #1 0x562414b2439e in test src/overflow.c:18
    #2 0x562414b2457f in main src/overflow.c:32
    #3 0x7fc53d445ccf  (/usr/lib/libc.so.6+0x27ccf) (BuildId: 8bfe03f6bf9b6a6e2591babd0bbc266837d8f658)

Direct leak of 40 byte(s) in 1 object(s) allocated from:
    #0 0x7fc53d6e0cc1 in __interceptor_calloc /usr/src/debug/gcc/gcc/libsanitizer/asan/asan_malloc_linux.cpp:77
    #1 0x562414b2458e in main src/overflow.c:33
    #2 0x7fc53d445ccf  (/usr/lib/libc.so.6+0x27ccf) (BuildId: 8bfe03f6bf9b6a6e2591babd0bbc266837d8f658)

Direct leak of 40 byte(s) in 1 object(s) allocated from:
    #0 0x7fc53d6e0cc1 in __interceptor_calloc /usr/src/debug/gcc/gcc/libsanitizer/asan/asan_malloc_linux.cpp:77
    #1 0x562414b241bf in test src/overflow.c:7
    #2 0x562414b24763 in main src/overflow.c:45
    #3 0x7fc53d445ccf  (/usr/lib/libc.so.6+0x27ccf) (BuildId: 8bfe03f6bf9b6a6e2591babd0bbc266837d8f658)

Direct leak of 40 byte(s) in 1 object(s) allocated from:
    #0 0x7fc53d6e0cc1 in __interceptor_calloc /usr/src/debug/gcc/gcc/libsanitizer/asan/asan_malloc_linux.cpp:77
    #1 0x562414b2439e in test src/overflow.c:18
    #2 0x562414b24763 in main src/overflow.c:45
    #3 0x7fc53d445ccf  (/usr/lib/libc.so.6+0x27ccf) (BuildId: 8bfe03f6bf9b6a6e2591babd0bbc266837d8f658)

Direct leak of 40 byte(s) in 1 object(s) allocated from:
    #0 0x7fc53d6e0cc1 in __interceptor_calloc /usr/src/debug/gcc/gcc/libsanitizer/asan/asan_malloc_linux.cpp:77
    #1 0x562414b241bf in test src/overflow.c:7
    #2 0x562414b2457f in main src/overflow.c:32
    #3 0x7fc53d445ccf  (/usr/lib/libc.so.6+0x27ccf) (BuildId: 8bfe03f6bf9b6a6e2591babd0bbc266837d8f658)

SUMMARY: AddressSanitizer: 200 byte(s) leaked in 5 allocation(s).
```

**Comment by stevearc** [comment]
Should be fixed!
